- .gitattributes
- README.md
- documentos/instrução.txt
- documentos/outros/instrução.txt
- imagens/instrução.txt
- src/Backend/instrução.txt
- src/Frontend/instrução.txt
* Adição dos arquivos do [template](https://github.com/Intelihub/Template_M2).
> Adiciona arquivos iniciais do projeto

- README.md
#Changelog 📝 
-Mudança do nome do Marcelo na parte de integrantes
> Altera nome de integrante ReadMe.md

- README.md
> altera o link do linkedin

- README.md
- apaga comentário do template do readme
> apaga parte desnecessária da estrutura de pasta

- src/controllers/professorControllers.js
- src/models/professorModels.js
- src/routes/routes.js
- Adicionei o endpoint de cadastro dos professores no controller;
- Adicionei o endpoint de cadastro dos professores no models;
- Adicionei o endpoint de cadastro dos professores no routes.
> Adiciona endpoint de cadastro do professor

- src/controllers/alunoControllers.js
- src/controllers/areaConhecimentoControllers.js
- src/controllers/avaliacaoControllers.js
- src/controllers/disciplinaControllers.js
- src/controllers/professorControllers.js
- src/models/areaConhecimentoModels.js
- src/models/avaliacaoModels.js
- src/models/disciplinaModels.js
- src/routes/routes.js
-  Endpoints tabela disciplina
-  Endpoints tabela avaliacao
-  Endpoints tabela area_conhecimento
> Endpoints tabelas disciplina, avaliacao e area_conhecimento

- src/models/areaConhecimentoModels.js
- src/models/avaliacaoModels.js
- src/models/disciplinaModels.js
- src/models/professorModels.js
- src/models/turmaModels.js
#Changelog 📝 
- arruma mensagem de confirmação no terminal
> fix: mensagem de confirmação da execução do endpoint

- src/controllers/blocoQuestaoControllers.js
- src/controllers/notaControllers.js
- src/models/blocoQuestaoModels.js
- src/models/notaModels.js
- src/routes/routes.js
- Endpoints de Leitura, Escrita, Atualização e Deleção de blocos de questões seguindo o padrão de projeto MVC
> Cria endpoints para a tabela bloco_questao

- package-lock.json
- package.json
- src/app.js
- src/controllers/notaControllers.js
- src/models/notaModels.js
- src/routes/routes.js
- src/views/css/login.css
- src/views/css/styles.css
- src/views/html/login.ejs
- src/views/index.ejs
- Adição de melhorias nos endpoints
- Correção semântica e estética do front
- Renderização ejs
> Atualizações do projeto

- src/views/css/login.css
- src/views/css/styles.css
- src/views/html/login.ejs
- Corrige tipos dos inputs do formulário de login
- Corrige estilização do formulário
> Melhorias semânticas e estéticas do formulário de login

- src/controllers/notaControllers.js
- Padroniza verificações dos endpoints de notas
> Corrige endpoints de nota

- src/views/css/perfil.css
- src/views/html/perfil.ejs
- Arruma cor do botão no mobile
- Arruma alinhamento do conteúdo no desktop
> Finalizando Tela de perfil

- package-lock.json
- src/controllers/alunoControllers.js
- src/routes/routes.js
-validações para os endpoints dos alunos
> Adiciona validações para os endpoints aluno

- README.md
- imagens/instrução.txt
- package.json
- Atualiza README com o passo a passo para rodar o projeto, o histório de lançamentos e a estrutura de pastas.
> Atualiza documento README do projeto

- src/controllers/professorControllers.js
- src/models/professorModels.js
- src/views/js/cabecalho.js
- Adição de mensagens de retorno para os endpoints dos professores
- Adição de comentários ao código
> Adiciona validações para os endpoints de professores

- src/views/css/cabecalho.css
- src/views/html/cabecalho.html
- Alterei o tamanho das letras;
- Aumentei a logo;
- Aumentei as barras;
- Aumentei a foto de perfil;
- Aumentei os botões.
> feat: adiciona responsividade cabeçalho (ipad)

- src/views/css/loginCadastro.css
- src/views/css/meusdados.css
- src/views/html/login.ejs
- src/views/html/meusdados.html
- src/views/html/register.ejs
- Adiciona html da página de meus dados
> Adiciona página de meus dados e corrige gramática

- src/views/css/cabecalho.css
- adiciona cor no backgroud do cabeçalho
> Arruma cabeçalho

- src/controllers/areaConhecimentoControllers.js
- src/controllers/avaliacaoControllers.js
- src/controllers/disciplinaControllers.js
- src/controllers/turmaControllers.js
- src/models/alunoModels.js
- src/models/areaConhecimentoModels.js
- src/models/avaliacaoModels.js
- src/models/blocoQuestaoModels.js
- src/models/disciplinaModels.js
- src/models/turmaModels.js
- src/routes/routes.js
- validação endpoint das disciplinas;
- validação endpoint das avaliações;
- validação endpoint das áreas de conhecimento;
- validação endpoint das turmas;
> feat: adiciona validações dos endpoints.

- src/views/css/assuntosDeAvaliacao.css
- src/views/html/assuntosDeAvaliacao.html
-Arruma distância entre assunto e matéria
-Arruma numeração dos assuntos
> Arrumando distância entre assunto e matéria e numeração dos assuntos

- src/views/css/cadastrarAluno.css
- src/views/css/listarAlunos.css
- src/views/html/cadastrarAluno.html
- src/views/html/listarAlunos.html
- adiciona tela de listar alunos
- adiciona tela de cadastrar alunos
> feat: adiciona tela de listar alunos e de cadastrar alunos

- src/views/css/aluno.css
- src/views/css/avaliacao.css
- src/views/css/styles.css
- src/views/html/aluno.html
- Adicionei a página individual dos alunos.
> fix: padroniza a página

- src/views/css/listarAlunos.css
- src/views/css/turma.css
- adiciona responsividade na tela listar alunos;
- adiciona responsividade na tela turma.
> feat:  responsividade em listar alunos e turma

- src/controllers/notaControllers.js
- src/models/notaModels.js
- src/models/turmaModels.js
- src/views/css/turma.css
- src/views/html/turma.ejs
- src/views/js/planosDeAula.js
- Criação do endpoint para retorno das notas de uma turma
- Criação do arquivo js para calcular média e, então, recomendar plano de aula vindo do Algolia da Nova Escola
> Implementação da Lógica de Recomendação de Planos de Aulas

- src/views/css/cabecalho.css
- src/views/html/aluno.html
- src/views/html/alunos.ejs
- src/views/html/cadastrarAluno.ejs
- src/views/html/login.ejs
- src/views/html/partials/cabecalho.ejs
- src/views/html/perfil.ejs
- src/views/js/cabecalho.js
- src/views/js/modoEscuro.js
- Une o HTML dos cabeçalhos mobile e desktop
- Cria JQuery para ajustar o código conforme a largura da tela.
> Responsividade do cabeçalho com JQuery

- src/views/html/aluno.html
- src/views/html/alunos.ejs
- src/views/html/assuntosDeAvaliacao.ejs
- src/views/html/atualizarAssunto.ejs
- src/views/html/avaliacao.html
- src/views/html/avaliacoes.ejs
- src/views/html/cadastrarAluno.ejs
- src/views/html/cadastrarAssunto.ejs
- src/views/html/cadastrarAvaliacao.ejs
- src/views/html/cadastrarTurma.ejs
- src/views/html/editarTurma.ejs
- src/views/html/erro.ejs
- src/views/html/index.ejs
- src/views/html/inserirResultados.ejs
- src/views/html/login.ejs
- src/views/html/meusdados.html
- src/views/html/partials/libras.ejs
- src/views/html/perfil.ejs
- src/views/html/planosDeAula.html
- src/views/html/register.ejs
- src/views/html/turma.ejs
- src/views/html/turmas.ejs
- adiciona leitor de libras em todas as telas
> Feat: adiciona leitor de libras nas telas
